using System;
using System.Drawing;
using System.Windows.Forms;

namespace Lab11
{
    public partial class Form1 : Form
    {
        // Declare the label control to be accessible throughout the class
        private Label statusLabel;

        public Form1()
        {
            InitializeComponent();
            SetupForm();
            SetupLabel();

            // Manually subscribe to the Form's KeyDown event
            this.KeyDown += new KeyEventHandler(Form1_KeyDown);

            // IMPORTANT: This allows the Form to receive key events 
            // even if a specific control (like the label) is focused.
            this.KeyPreview = true;
        }

        private void SetupForm()
        {
            this.Text = "Form1 - Keyboard Effects (A, B, C)";
            this.Size = new Size(600, 400);
            this.BackColor = Color.White; // Default/Initial Background Color
        }

        private void SetupLabel()
        {
            statusLabel = new Label();
            statusLabel.Text = "Press A, B, or C";

            // Initial/Default properties for the Label
            statusLabel.Font = new Font("Segoe UI", 14, FontStyle.Regular);
            statusLabel.ForeColor = Color.Black;
            statusLabel.AutoSize = true;

            // Add the label to the form's controls collection
            this.Controls.Add(statusLabel);

            // Set initial location (Centered)
            CenterLabel();
        }

        // Helper function to re-center the label after a font size change
        private void CenterLabel()
        {
            // Ensure the label's dimensions are calculated before centering
            statusLabel.Refresh();
            int x = (this.ClientSize.Width - statusLabel.Width) / 2;
            int y = (this.ClientSize.Height - statusLabel.Height) / 2;
            statusLabel.Location = new Point(x, y);
        }

        // --- Event Handler for KeyDown: Handles A, B, and C ---
        private void Form1_KeyDown(object sender, KeyEventArgs e)
        {
            // Use e.KeyCode to check which key was pressed
            if (e.KeyCode == Keys.A)
            {
                // Key 'A' Effect (Original Request)
                statusLabel.Font = new Font("Verdana", 20, FontStyle.Bold);
                statusLabel.ForeColor = Color.Turquoise;
                this.BackColor = Color.White;
                statusLabel.Text = "Hello World (Key A)";
            }
            else if (e.KeyCode == Keys.B)
            {
                // Key 'B' Effect
                statusLabel.Font = new Font("Arial", 24, FontStyle.Italic);
                statusLabel.ForeColor = Color.Fuchsia;
                this.BackColor = Color.LightYellow;
                statusLabel.Text = "Key B Pressed!";
            }
            else if (e.KeyCode == Keys.C)
            {
                // Key 'C' Effect
                statusLabel.Font = new Font("Times New Roman", 16, FontStyle.Underline);
                statusLabel.ForeColor = Color.DarkGreen;
                this.BackColor = Color.LightGray;
                statusLabel.Text = "C Action Triggered.";
            }

            // After any change, re-center the label due to font size changes
            CenterLabel();

            // Indicate that the key press was handled
            e.SuppressKeyPress = true;
        }

        // Required method (usually generated by the designer, but we include it)
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(600, 400); // Set initial size here too
            this.Name = "Form1";
            this.ResumeLayout(false);
        }
    }
}